{"name": "Request github repositories for the user", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\shash\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\shash\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\create_user_steps.py\", line 54, in step_impl\n    assert context.response.status_code == status_code\n"}, "steps": [{"name": "Given request url and user credentials are available", "status": "passed", "start": 1628252143445, "stop": 1628252143447}, {"name": "When I send the request to github api", "status": "passed", "start": 1628252143448, "stop": 1628252144002}, {"name": "Then User repos are return successfully and status code is 200", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\shash\\anaconda3\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\shash\\anaconda3\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\create_user_steps.py\", line 54, in step_impl\n    assert context.response.status_code == status_code\n"}, "start": 1628252144003, "stop": 1628252144004}], "start": 1628252143444, "stop": 1628252144007, "uuid": "6d9a9a66-1855-4f7c-95a4-7d9396847565", "historyId": "13f581ef98a5e74e2d3a7e446322c32e", "fullName": "Handle Authentication: Request github repositories for the user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Handle Authentication"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}